version: 2
jobs:
  build:
    docker:
      - image: scionproto/scion_base
    working_directory: /tmp/go/src/github.com/netsec-ethz/rains
    steps:
      - run:
          name: setup envvar
          command: |
              echo 'export GOPATH=/tmp/go' >> $BASH_ENV
              echo 'export PATH=$PATH:/tmp/go/bin' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - v2-pkg-cache
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: scion
          command: |
            sudo apt-get install --assume-yes libpcap0.8 libpcap0.8-dev 
            mkdir -p $GOPATH/src/github.com/scionproto/scion
            git clone https://github.com/netsec-ethz/netsec-scion $GOPATH/src/github.com/scionproto/scion
            cd $GOPATH/src/github.com/scionproto/scion
            ./env/deps
            make
      - run:
          name: run build
          command: |
            dep ensure
            go build -v cmd/rainsd/rainsd.go
            go build -v cmd/rdig/rdig.go
            go build -v cmd/zonepub/zonepub.go
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./internal/...
            go vet ./cmd/...
            go vet ./test/...
            go test ./internal/pkg/...
            go test -v ./test/integration/
      - save_cache:
          key: v2-pkg-cache
          paths:
            - "/tmp/go/pkg"
